dict_gts_sensor = {'waka': 'rad', 'abas': 'rad', 'hana': 'rad', 'fuka': 'rad', 'ofun': 'rad', 'sado': 'rad',
                   'toya': 'rad', 'mera': 'rad', 'omae': 'rad', 'kusm': 'rad', 'saig': 'rad', 'hmda': 'rad',
                   'tosa': 'rad', 'naga': 'rad', 'naha': 'rad', 'subi': 'prs', 'mani': 'prs', 'luba': 'prs',
                   'lega': 'prs', 'davo': 'ra2', 'prs': 'aqu', 'brom': 'aqu', 'pmur': 'rad', 'capc': '(m)',
                   'espe': 'aqu', 'thev': 'prs', 'porl': 'aqu', 'barn': 'aqu', 'sprg': 'aqu', 'bapj': 'rad',
                   'spjy': 'rad', 'tbwc': 'rad', 'pkem': 'aqu', 'ferg': 'aqu', 'lirf': 'rad', 'trst': 'aqu',
                   'tare': 'rad', 'honb': '(m)', 'litz': 'rad', 'vanu': 'aqu', 'lena': 'rad', 'hien': 'prs',
                   'ouve': 'prs', 'levu': 'aqu', 'upol': 'prs', 'pagx': 'pwl', 'pago': 'pwl', 'ncpt': 'prs',
                   'mnkt': 'prs', 'taut': 'prs', 'lott': 'prs', 'gist': 'prs', 'napt': 'prs', 'cpit': 'prs',
                   'wlgt': 'prs', 'otat': 'prs', 'chit': 'prs', 'quep': 'prs', 'psds': 'prs', 'laun': 'prs',
                   'acaj': 'rad', 'huat': 'rad', 'hua2': 'rad', 'ptan': 'rad', 'zihu': 'rad', 'laz2': 'rad',
                   'laza': 'rad', 'manz': 'rad', 'pval': 'rad', 'lpaz': 'rad', 'tuxp': 'rad', 'tux2': 'rad',
                   'smag': 'rad', 'ccar': 'flt', 'imuj': 'rad', 'sand': 'pwl', 'lajo': 'pwl', 'pslu': 'pwl',
                   'mont': 'pwl', 'alam': 'pwl', 'fpnt': 'wls', 'cres': 'pwl', 'char': 'pwl', 'asto': 'pwl',
                   'wpwa': 'pwl', 'epme': 'pwl', 'cwme': 'pwl', 'ptme': 'pwl', 'boma': 'pwl', 'woma': 'pwl',
                   'mony': 'pwl', 'bgct': 'pwl', 'cmnj': 'pwl', 'cbmd': 'pwl', 'dpnc': 'wls', 'benc': 'pwl',
                   'fpga': 'pwl', 'pnfl': 'pwl', 'wlms': 'wls', 'psla': 'pwl', 'gila': 'wls', 'cpla': 'wls',
                   'gptx': 'bwl', 'lime': 'pwl', 'stcr': 'pwl', 'lame': 'pwl', 'amal': 'pwl', 'viqu': 'pwl',
                   'vieq': 'pwl', 'yabu': 'wls', 'sanj': 'pwl', 'sapr': 'pwl', 'arec': 'pwl', 'gypr': 'pwl',
                   'maya': 'pwl', 'sana': 'prs', 'limn': 'prs', 'elpo': 'rad', 'sapz': 'rad', 'sama': 'prs',
                   'bull': 'prs', 'ptsp': 'rad', 'pric': 'prs', 'calq': 'bat(V)', 'stlu': 'rad', 'ftfr': 'rad',
                   'rose': 'rad', 'ptmd': 'rad', 'ptpt': 'rad', 'desh': 'rad', 'blow': 'rad', 'ppla': 'prs',
                   'cher': 'rad', 'rodr': 'prs', 'blue': 'prs', 'lamu': 'prs', 'sala': 'prs', 'masi': 'prs',
                   'marm': 'prs', 'hani': 'rad', 'colo': 'prs', 'trna': 'prs', 'chen': 'prs', 'ptbl': 'prs',
                   'lang': 'prs', 'kol2': 'prs', 'koli': 'prs', 'cili': 'rad', 'sema': 'prs', 'prig': 'prs',
                   'sura': 'prs', 'saum': 'prs', 'quar': 'flt', 'shek': 'flt', 'shen': 'rad', 'zhap': 'rad',
                   'qing': 'rad'}
""" 每个 code 对应一个主 sensor"""

dict_unique_sensors = {'abas': 'enc', 'acaj': 'rad', 'alam': 'pwc', 'amal': 'pwl', 'arec': 'pwl', 'asto': 'pwl',
                       'bapj': 'rad', 'barn': 'prs', 'benc': 'pwl', 'bgct': 'pwl', 'blow': 'rad', 'blue': 'prs',
                       'boma': 'pwl', 'brom': 'prs', 'bull': 'prs', 'calq': 'pr1', 'capc': 'prs', 'cbmd': 'pwl',
                       'ccar': 'rad', 'char': 'pwl', 'chen': 'prs', 'cher': 'rad', 'chit': 'prs', 'cili': 'rad',
                       'cmnj': 'pwl', 'colo': 'prs', 'cpit': 'prs', 'cpla': 'bwl', 'cres': 'pwl', 'cwme': 'pwl',
                       'darw': 'prs', 'davo': 'rad', 'desh': 'rad', 'dpnc': 'bwl', 'elpo': 'rad', 'epme': 'pwl',
                       'espe': 'prs', 'ferg': 'prs', 'fpga': 'pwl', 'fpnt': 'pwl', 'ftfr': 'rad', 'fuka': 'enc',
                       'gila': 'pwl', 'gist': 'prs', 'gptx': 'bwl', 'gypr': 'pwl', 'hana': 'enc', 'hani': 'rad',
                       'hien': 'prs', 'hmda': 'enc', 'honb': 'prs', 'hua2': 'rad', 'huat': 'rad', 'imuj': 'rad',
                       'koli': 'prs', 'kusm': 'enc', 'lajo': 'pwl', 'lame': 'pwl', 'lamu': 'prs', 'lang': 'prs',
                       'laun': 'prs', 'laz2': 'rad', 'laza': 'flt', 'lega': 'prs', 'lena': 'rad', 'levu': 'prs',
                       'lime': 'pwl', 'limn': 'prs', 'lirf': 'rad', 'litz': 'rad', 'lott': 'prs', 'lpaz': 'rad',
                       'luba': 'prs', 'mani': 'prs', 'manz': 'rad', 'marm': 'prs', 'masi': 'rad', 'maya': 'pwl',
                       'mera': 'enc', 'mnkt': 'prs', 'mony': 'pwl', 'naga': 'enc', 'naha': 'enc', 'napt': 'prs',
                       'ncpt': 'prs', 'ofun': 'enc', 'omae': 'enc', 'otat': 'prs', 'ouve': 'prs', 'pago': 'pwc',
                       'pkem': 'prs', 'pmur': 'prs', 'pnfl': 'pwl', 'porl': 'prs', 'ppla': 'prs', 'pric': 'prs',
                       'psla': 'pwl', 'pslu': 'pwl', 'ptbl': 'prs', 'ptmd': 'p1', 'ptme': 'pwl', 'ptpt': 'rad',
                       'ptsp': 'rad', 'pval': 'rad', 'qing': 'rad', 'quar': 'flt', 'quep': 'prs', 'rodr': 'prs',
                       'rose': 'rad', 'sado': 'enc', 'saig': 'enc', 'sala': 'prs', 'sama': 'prs', 'sana': 'prs',
                       'sand': 'pwl', 'sanj': 'pwl', 'sapr': 'pwl', 'sapz': 'rad', 'sema': 'prs', 'shek': 'prs',
                       'shen': 'rad', 'smag': 'rad', 'spjy': 'rad', 'sprg': 'prs', 'stcr': 'pwl', 'stlu': 'rd',
                       'subi': 'prs', 'sura': 'prs', 'tare': 'rad', 'taut': 'prs', 'tbwc': 'rad', 'thev': 'prs',
                       'tosa': 'enc', 'toya': 'enc', 'trna': 'prs', 'trst': 'aqu', 'tux2': 'rad', 'tuxp': 'flt',
                       'upol': 'prs', 'vanu': 'prs', 'vieq': 'pwl', 'viqu': 'pwl', 'waka': 'enc', 'wlgt': 'prs',
                       'wlms': 'pwl', 'woma': 'pwl', 'wpwa': 'pwc', 'yabu': 'pwl', 'zihu': 'rad'}
"""经过处理后的 code 对应 唯一 sensor"""
