version: "3"

services:
  global_surge_forecast_job:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: py37:1.27
    container_name: global-surge-forecast-coverageserver
    working_dir: /opt/project
    privileged: true
    command:
      - /bin/bash
    tty: true
    volumes:
      - /home/surge/pro/global_surge_forecast_coverageserver:/opt/project
      - /home/surge/DATA_LOCAL/GLOBAL_FORECAST:/data/local


